name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config core.excludesFile .gitignore
          echo "*.png" >> .gitignore
          echo "*.ttf" >> .gitignore
          echo ".github/" >> .gitignore
      - name: Setup Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git rm -r --cached .
          git add .
          git commit -m "Update repository and configure Git LFS" || echo "No changes to commit"
          git push -f https://MakiAi:$HF_TOKEN@huggingface.co/spaces/MakiAi/pic-to-header main
